name: .github/workflows/ci.yml

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 towncrier

    - name: Check newsfragment format
      run: towncrier --draft
      id: towncrier

    - name: Check syntax with flake8
      run: flake8 nucypher/ --count --select=E9,F63,F7,F82 --show-source --statistics
      id: flake8

    - name: Run tests
      run: pytest
      id: tests

    - name: Print error logs if failure
      if: failure()
      run: |
        echo "Error in step: ${{ steps.tests.outcome }}"
        cat logs/error.log  # Assuming tests or other steps output detailed logs to this file

    - name: Retry logic for external dependencies
      run: |
        retry_count=0
        max_retries=3
        until [ $retry_count -ge $max_retries ]
        do
          command_to_run_external_service && break
          retry_count=$((retry_count+1))
          sleep 10
        done
      id: external-dependencies
