name: Error Handling Enhancements

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  error_handling:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - name: Notify on Slack
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Create GitHub Issue
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueTitle = `CI Failure: ${github.event.workflow_run.head_commit.message}`;
            const issueBody = `The Continuous Integration workflow failed for commit ${github.event.workflow_run.head_commit.id}. Please investigate the failure. Workflow URL: ${github.event.workflow_run.html_url}`;
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['CI', 'bug']
            });
