name: Main CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Print Python version and installed packages
      run: python -m pip list
    - name: Run Tests
      run: |
        set -e
        python -m pytest tests/
      if: always()
    - name: Capture logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: path/to/logs/
    - name: Lint
      run: |
        set -e
        python -m flake8 .
      if: always()
    - name: Capture linting logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: lint-logs
        path: path/to/lint-logs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Print Python version and installed packages
      run: python -m pip list
    - name: Deploy
      run: |
        set -e
        python deploy_script.py
      if: always()
    - name: Capture deployment logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: deployment-logs
        path: path/to/deployment-logs/
