name: Preemptive Checks

on:
  pull_request:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Check Syntax
        run: |
          python -m compileall -f .

  linter-check:
    runs-on: ubuntu-latest
    needs: syntax-check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Linter
        run: pip install flake8
      - name: Run Linter
        run: flake8 .

  test-suite:
    runs-on: ubuntu-latest
    needs: linter-check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        run: pytest
